/* Fixed visual layouts over the app allocator's witness. No extra allocation. */
(function(root){
  'use strict';
  const E=typeof module!=='undefined'&&module.exports?require('./evidence_core.js'):root.EchoEvidenceCore;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
  const short=v=>Number(v).toLocaleString('en-US',{maximumFractionDigits:1});
  const label=p=>({HA_early:'Early A',HA_late:'Late A',PharmaA:'Pharma',Hand1_late:'Late A + Pharma',HB_all:'Herbal B'}[p]||p);
  const seg=(name,items,current)=>`<div class="ev-seg" role="group" aria-label="${esc(name)}">${items.map(([v,t])=>`<button data-setting="${name}" data-value="${v}" aria-pressed="${v===current}">${esc(t)}</button>`).join('')}</div>`;
  function group(s,w,level){
    const x=s.words[w],g=x.g.toUpperCase();if(level==='words')return w;if(level==='gallows')return g;
    const t=x.tail,end=/^(ol|or|eol|eor)$/.test(t)?'ol / or':/^(ar|al)$/.test(t)?'ar / al':t==='y'?'y':t==='edy'?'edy':/^(eey|eedy)$/.test(t)?'ee':/^(chy|shy|chey|shey|chedy|shedy|chdy|shdy)$/.test(t)?(t.startsWith('ch')?'ch':'sh'):t==='aiin'?'aiin':t==='ain'?'ain':'other';
    return g+' · '+end;
  }
  function layout(s,f,target,c,{basis='stock',allocation='after',grouping='gallows',focus=''}={}){
    const a=E.rates(s,f,s.source),b=E.rates(s,f,target),z=allocation==='before'?c.base:c.withRule,rr=z.routes.map(r=>({...r}));
    if(basis==='signed')for(const w of f.words){const mass=Math.min(a.get(w),b.get(w));if(mass>1e-8)rr.push({from:w,to:w,mass});}
    const focused=rr.filter(r=>r.from===focus||r.to===focus),activeA=new Set(focused.map(r=>r.from)),activeB=new Set(focused.map(r=>r.to));
    if(focus){activeA.add(focus);activeB.add(focus);}
    const edgeMap=new Map(f.routes.map(r=>[r.source+'>'+r.target,r]));
    const nodes=(rates,p)=>{const out=new Map();for(const w of f.words){if(rates.get(w)<=1e-8)continue;const id=group(s,w,grouping);
      if(!out.has(id))out.set(id,{id,g:s.words[w].g,words:[],mass:0,count:0,used:0,active:false});const q=out.get(id);q.words.push(w);q.mass+=rates.get(w);q.count+=s.words[w].count[p];q.active||=(p===s.source?activeA:activeB).has(w);}
      return [...out.values()].sort((u,v)=>(grouping==='words'&&focus?Number(v.active)-Number(u.active):0)||u.g.localeCompare(v.g)||u.id.localeCompare(v.id));};
    const left=nodes(a,s.source),right=nodes(b,target),lm=new Map(left.map(n=>[n.id,n])),rm=new Map(right.map(n=>[n.id,n])),pool=new Map();
    for(const r of rr){const from=group(s,r.from,grouping),to=group(s,r.to,grouping),trace=edgeMap.get(r.from+'>'+r.to),kind=r.from===r.to?'kept':trace?.exchange?'swap':'edited',key=[from,to,kind].join('|');
      if(!pool.has(key))pool.set(key,{from,to,kind,mass:0,routes:[]});const q=pool.get(key);q.mass+=r.mass;q.routes.push({...r,steps:trace?.steps||[]});lm.get(from).used+=r.mass;rm.get(to).used+=r.mass;}
    const gap=grouping==='words'?42:30,height=360+Math.max(left.length,right.length,2)*gap,scale=300/Math.max(z.source,z.target,1);
    for(const ns of [left,right]){let y=48;for(const q of ns){q.y=y;q.height=q.mass*scale;q.rest=Math.max(0,q.mass-q.used);q.offset=0;y+=q.height+gap;}}
    const links=[...pool.values()].sort((u,v)=>left.indexOf(lm.get(u.from))-left.indexOf(lm.get(v.from))||right.indexOf(rm.get(u.to))-right.indexOf(rm.get(v.to))||u.kind.localeCompare(v.kind));
    for(const l of links){const x=lm.get(l.from),y=rm.get(l.to);l.width=l.mass*scale;l.y1=x.y+x.offset;l.y2=y.y+y.offset;x.offset+=l.width;y.offset+=l.width;
      l.path=`M 176 ${l.y1} C 350 ${l.y1}, 450 ${l.y2}, 624 ${l.y2} L 624 ${l.y2+l.width} C 450 ${l.y2+l.width}, 350 ${l.y1+l.width}, 176 ${l.y1+l.width} Z`;}
    return {left,right,links,height,scale,credit:z.credit,unplaced:z.unplaced,unfilled:z.unfilled};
  }
  function flow(s,f,c,state){
    const m=layout(s,f,state.target,c,state),aria=`${label(s.source)} to ${label(state.target)}. ${state.allocation==='after'?'With the swap.':'Baseline.'} ${n(m.credit)} units are matched.`;
    const nodes=(ns,left)=>ns.map(x=>{const bx=left?164:624,tx=left?152:648;return `<g class="ev-flow-node ${state.focus&&!x.active?'ev-dim':''}"><title>${esc(x.id)} has ${x.count} ${x.count===1?'word':'words'}. ${n(x.mass)} per 10,000. ${n(x.rest)} remain unmatched.</title><rect x="${bx}" y="${x.y}" width="12" height="${Math.max(.35,x.height)}" class="ev-${x.g}"/>${x.rest>1e-8?`<rect x="${bx}" y="${x.y+x.used*m.scale}" width="12" height="${x.rest*m.scale}" fill="url(#ev-gap)"/>`:''}<text x="${tx}" y="${x.y+x.height/2-2}" text-anchor="${left?'end':'start'}">${esc(x.id)}</text><text class="ev-svg-small" x="${tx}" y="${x.y+x.height/2+14}" text-anchor="${left?'end':'start'}">${short(x.mass)}</text></g>`;}).join('');
    return {m,html:`<svg class="ev-sankey" viewBox="0 0 800 ${m.height}" role="group" aria-label="${esc(aria)}"><defs><pattern id="ev-gap" width="6" height="6" patternUnits="userSpaceOnUse"><rect width="6" height="6" class="ev-gap-bg"/><path d="M-1 1L1-1 M0 6L6 0 M5 7L7 5" class="ev-gap-line"/></pattern></defs><text x="164" y="22" text-anchor="end" class="ev-svg-heading">${esc(label(s.source))}</text><text x="636" y="22" class="ev-svg-heading">${esc(label(state.target))}</text>${m.links.map((l,i)=>`<path d="${l.path}" class="ev-ribbon ev-${l.kind} ${state.focus&&!l.routes.some(r=>r.from===state.focus||r.to===state.focus)?'ev-dim':''}" data-flow="${i}" tabindex="0" role="button" aria-label="${esc(l.from+' to '+l.to+' '+n(l.mass)+' per 10,000 words')}"><title>${esc(l.from+' → '+l.to)}. ${n(l.mass)} per 10,000 words. ${l.routes.length} word pairs. Select to inspect.</title></path>`).join('')}${nodes(m.left,true)}${nodes(m.right,false)}${!m.links.length?'<text x="400" y="130" text-anchor="middle">No words can be matched.</text>':''}</svg>`};
  }
  function sections(s,f,state,labels={kLabel:'K words',tLabel:'T words'}){
    const rows=s.sections.map(p=>({...p,...E.ratio(s,f,p.key)})),max=state.measure==='share'?100:Math.max(1,...rows.flatMap(r=>[r.kRate,r.tRate]));
    return `<section class="ev-sections" id="ev-sections"><div class="ev-section-title"><div class="ev-legend"><span><i class="ev-k"></i>${esc(labels.kLabel)}</span><span><i class="ev-t"></i>${esc(labels.tLabel)}</span></div><div class="ev-legend">${seg('measure',[['rate','Frequency'],['share','Share']],state.measure)}</div></div><div class="ev-populations">${rows.map(r=>{
      const k=state.measure==='share'?(r.share??0)*100:r.kRate,t=state.measure==='share'?(r.share===null?0:(1-r.share)*100):r.tRate,unit=state.measure==='share'?'%':'';
      const body=`<span class="ev-pop-name">${esc(label(r.key))}${r.key==='Hand1_late'?'<small>Pooled</small>':''}</span><span class="ev-columns"><span class="ev-column"><b>${state.measure==='share'&&r.share===null?'—':short(k)+unit}</b><i class="ev-k" style="height:${k/max*72}px"></i><small>${esc(labels.kLabel)}</small></span><span class="ev-column"><b>${state.measure==='share'&&r.share===null?'—':short(t)+unit}</b><i class="ev-t" style="height:${t/max*72}px"></i><small>${esc(labels.tLabel)}</small></span></span><span class="ev-pop-count">${r.k+r.t} ${r.k+r.t===1?'word':'words'}</span>`;
      const tip=`${r.label}. K occurs ${r.k} times and T occurs ${r.t} times. The section contains ${r.N} words.`;
      return r.key===s.source?`<div class="ev-pop ev-source" title="${esc(tip)}">${body}</div>`:`<button class="ev-pop ${r.key===state.target?'selected':''} ${r.key==='Hand1_late'?'pooled':''}" data-target="${r.key}" aria-pressed="${r.key===state.target}" title="${esc(tip)}">${body}</button>`;
    }).join('')}</div><div class="ev-chart-foot"><span>${state.measure==='share'?'Bars show each gallows’ share of this family.':'Bars show occurrences per 10,000 words.'} Counts beneath the bars are occurrences, not distinct spellings.</span></div></section>`;
  }
  function gain(c,swapMass=0){const allocationNote=swapMass>c.gain+1e-7?`The swap allocation carries ${n(swapMass)} through t → k, adding ${n(c.gain)} overall. Some baseline matches are displaced.`:'The ribbons show one possible allocation.';const den=Math.max(c.base.target,c.withRule.credit,1),width=v=>100*Math.max(0,v)/den;
    return `<aside class="ev-gain"><h4>Added matches</h4><div class="ev-gain-number">${c.gain>1e-7?'+':''}${n(Math.abs(c.gain)<1e-7?0:c.gain)}</div><p>${c.gain>1e-7?'The swap allows more words to be matched.':'The swap adds no matches.'}</p><small>per 10,000 words</small><div class="ev-coverage"><div><span>Baseline</span><b>${n(c.base.credit)}</b></div><div class="ev-meter"><i style="width:${width(c.base.credit)}%"></i></div><div><span>With swap</span><b>${n(c.withRule.credit)}</b></div><div class="ev-meter"><i style="width:${width(c.base.credit)}%"></i><i class="ev-added" style="width:${width(c.gain)}%"></i></div></div><div class="ev-remaining"><h4>Unmatched</h4><div><span>Baseline</span><b>${n(c.base.unfilled)}</b></div><div><span>With swap</span><b>${n(c.withRule.unfilled)}</b></div></div><p class="ev-allocation-note">${allocationNote}</p><p class="ev-limit">Rules set the maximum possible match. The data do not establish how often they were used.</p></aside>`;
  }
  function finding(s,f,c,state,t){
    const a=E.ratio(s,f,s.source),b=E.ratio(s,f,state.target),target=label(state.target),pct=x=>short(x*100)+'%';
    const observation=a.share===null?`Early A has no observations of this family. ${target} has ${b.k+b.t}.`:b.share===null?`${target} has no observations of this family.`:`Within this family, K accounts for ${pct(a.share??0)} in early A and ${pct(b.share)} in ${target}. The family’s frequency changes from ${short(a.totalRate)} to ${short(b.totalRate)} per 10,000 words.`;
    let note='';
    if(f.id==='ykaiin'&&state.target==='HB_all')note='The more common gallows changes from T to K. The later K share is 15.2 points from the exact inverted prediction. The intermediate sections are too sparse to confirm the pattern.';
    else if(f.id==='okal')note='otol and otchy compete for the same targets. The flow keeps both in one shared budget.';
    else if(f.id==='qokal')note=t.gain>1e-7?`This family contributes ${short(c.gain/t.gain*100)}% of all added matches in ${target}. The other families add ${n(t.gain-c.gain)} per 10,000 words.`:'This family adds no matches under these settings.';
    return {observation,note};
  }
  const rulePatterns={d:'y → dy',ed:'chy or shy → edy',B1:'eol or eor → edy',C1:'chol or shol → cheol or sheol → chedy or shedy',C3:'chy or shy → chey or shey → chedy or shedy',C4:'kol or tol → keol or teol → kedy or tedy',S1:'o → eo after ch or sh',S4:'o → e between a bench and a gallows',EE_Y:'Gy → Geey',GY_AR:'Gy → Gar',GEDY_AR:'Gedy → Gar',GEDY_AL:'Gedy → Gal',KT_CORR:'t → k'};
  function ruleKey(){return '<details class="ev-rule-key"><summary>Rule key</summary><p>G stands for k or t. These patterns name the edits. The source restrictions and composition limits above still apply. The liquid rules also accept final r in place of l.</p><dl>'+Object.entries(rulePatterns).map(([k,v])=>`<div><dt><code>${k}</code></dt><dd>${esc(v)}</dd></div>`).join('')+'</dl></details>';}
  function method(s,f,c){return `<div class="ev-method-grid"><section><h4>Counts</h4><p>Each comparison starts with early Herbal A. Late A and Pharma are also shown as a pooled sample. That sample is not independent of its two parts.</p><p>Herbal B includes herbal pages only. Folio f76r belongs to Bio. Leading q is preserved, and repeated words are counted separately.</p><p>This study includes words with exactly one ordinary k or t. It excludes p, f and compound bench signs such as ckh and cth.</p></section><section><h4>Rules</h4><p>The existing rules change vowels and endings while preserving k and t. The exchange adds a separate, optional t → k step. Open the rule key below to see each operation.</p><p>The baseline includes ${s.baseline.map(esc).join(', ')}. Up to two ordinary edits may combine, except S4 cannot combine with d or ed. The EE_Y change may follow them, with an optional d or B1. One change to an ar or al ending may follow that. The optional t → k change comes last.</p><p>The o condition tests the original source. S3, S3_CH, EE_O and standalone S2 are off. Middle spellings drawn within a composite rule do not permit additional standalone edits.</p><p>This saved study is independent of the global rule selection and repeat setting.</p></section><section><h4>Accounting</h4><p>“Across all observations” lets retained and transformed spellings compete for the full source and target frequencies. “After keeping shared spellings” reserves the frequency already present in both sections, then matches only source surpluses to target shortages.</p><p>The minimum count applies only to added exchanges. Each original source and final target must have at least three observations. Every baseline competitor remains.</p><p>All ${f.words.length} spellings share source and target limits. Display filters never change these limits. Optional routes can only increase the maximum coverage.</p></section><section><h4>Limits</h4><p>The diagram shows one possible allocation. Other allocations may cover the same amount. The amount on a ribbon is not its individual gain.</p><p>This is an upper bound, not an estimated application rate or proof of historical ancestry. Late A and Pharma do not act as required stops on the way to Herbal B.</p><p>Across target spellings, coverage rises by ${n(c.grossGain)} and falls by ${n(c.loss)} in this allocation. Their difference is ${n(c.gain)} per 10,000 words.</p><p>The older Network and Sections views merge q variants and include exploratory substeps and reverse links. Their results are not interchangeable with this fixed comparison.</p></section></div>`;}
  const api={layout,flow,sections,gain,method,seg,label,finding,ruleKey};if(typeof module!=='undefined'&&module.exports)module.exports=api;else root.EchoEvidenceVisuals=api;
})(typeof window!=='undefined'?window:globalThis);
