/* One comparison and one measurement across all family charts. */
(function(root){
  'use strict';
  const C=root.EchoEvidencePatternsCore,S=root.EchoEvidenceSlopeChart;
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const n=v=>Number(v).toLocaleString('en-US',{maximumFractionDigits:1});
  const names={HA_early:'Early Herbal A',HA_late:'Late Herbal A',PharmaA:'Pharma',Hand1_late:'Late A + Pharma',HB_all:'Herbal B'};
  const classes={inverted:'Approximate inversion',stable:'Similar ratio',reversal:'Reversed majority',shift:'Different ratio',balanced:'Early ratio near equality',insufficient:'Too few observations'};
  const verdicts={inverted:'The inverted early share passes this share-only test.',stable:'The unchanged early share passes this share-only test.',reversal:'The majority changes. Neither prediction passes this share-only test.',shift:'Neither prediction passes this share-only test.',balanced:'The early proportions are too close to equality to distinguish the two predictions.',insufficient:'The section has too few observations for the share-only test.'};
  const opt=(v,t,x)=>`<option value="${v}" ${String(v)===String(x)?'selected':''}>${t}</option>`;
  function label(s,g){
    if(g.level&&g.level!=='pool')return esc(g.label);
    if(g.mode==='pairs')return esc(g.label);
    if(g.words.length<=2)return g.words.map(esc).join(' / ');
    const prefixes=[...new Set(g.words.map(w=>s.words[w].prefix))].sort();
    if(prefixes.length===1)return `${esc(prefixes[0])}k* / ${esc(prefixes[0])}t*`;
    return `${prefixes.map(esc).join(', ')} + k/t`;
  }
  function counts(s,g,state){
    const a=g.bySection[s.source],b=g.bySection[state.patternTarget],c=g.comparisons[state.patternTarget],frames=new Map();
    for(const w of g.words){const r=s.words[w],key=r.prefix+'|'+r.tail;if(!frames.has(key))frames.set(key,{k:r.prefix+'k'+r.tail,t:r.prefix+'t'+r.tail});}
    const ratio=r=>r.total===0?'—':r.t===0?'∞':n(r.k/r.t);
    return `<section class="ef-detail" aria-label="${label(s,g)} details"><header><h3>${label(s,g)}</h3><button class="wb-button" data-pattern-expand="${esc(g.id)}">Close details</button></header>
      <p>${g.mode==='pairs'?'The two spellings differ only in k or t.':'Candidate transformation rules connect the spellings in this pool. Its individual pairs are not independent confirmations.'}</p>
      <h4>Section counts</h4><div class="ev-scroll"><table class="ev-table"><thead><tr><th>Section</th><th>K count</th><th>T count</th><th>K per 10k</th><th>T per 10k</th><th>Total per 10k</th><th>K share</th><th>K/T</th></tr></thead><tbody>${s.sections.map(p=>{const r=g.bySection[p.key];return `<tr class="${p.key===state.patternTarget?'ev-selected':''}"><th>${names[p.key]}<small>${p.N.toLocaleString()} section words</small></th><td>${r.k}</td><td>${r.t}</td><td>${n(r.kRate)}</td><td>${n(r.tRate)}</td><td>${n(r.totalRate)}</td><td>${r.share===null?'—':n(r.share*100)+'%'}</td><td>${ratio(r)}</td></tr>`;}).join('')}</tbody></table></div>
      <h4>Ratio check</h4><p>${names[state.patternTarget]} is ${n(b.share*100)}% K. Compare that observation with the two predictions from early A.</p><table class="ev-table ef-ratio-table"><thead><tr><th>Prediction</th><th>K share</th><th>Gap from observation</th></tr></thead><tbody><tr><th>Keep the early ratio</th><td>${n(a.share*100)}%</td><td>${n(c.identityError*100)} percentage points</td></tr><tr><th>Invert the early ratio</th><td>${n((1-a.share)*100)}%</td><td>${n(c.mirrorError*100)} percentage points</td></tr></tbody></table><p>${verdicts[c.classification]}</p>
      <details><summary>Ratio method</summary><p>An approximate inversion must be within 10 percentage points of the inverted early K share and at least 10 points closer than the unchanged share. Similar ratio applies the converse test. Early shares between 45% and 55% make the predictions too close to distinguish. Reversed majority records a crossing that fails the stricter inversion test. These descriptive thresholds are not confidence estimates.</p></details>
      <details class="ef-members"><summary>All ${g.words.length} spellings</summary><p>Numbers below are raw K / T observations. Unobserved counterparts have zero counts.</p><div class="ef-member-scroll" tabindex="0"><table class="ev-table"><thead><tr><th>Spellings</th>${s.sections.map(p=>`<th>${names[p.key]}</th>`).join('')}</tr></thead><tbody>${[...frames.values()].sort((a,b)=>a.k.localeCompare(b.k)).map(r=>`<tr><th><code>${esc(r.k)} / ${esc(r.t)}</code></th>${s.sections.map(p=>`<td>${s.words[r.k]?.count[p.key]||0} / ${s.words[r.t]?.count[p.key]||0}</td>`).join('')}</tr>`).join('')}</tbody></table></div></details>
      <button class="wb-button" data-pattern-inspect="${esc(g.poolId||g.poolIds[0])}">Inspect the complete pool’s rules and flow</button></section>`;
  }
  function html(s,state){
    const data=C.build(s,{mode:state.patternMode,minimum:state.patternMin,target:state.patternTarget}),rows=data.groups;
    const page=Math.min(state.patternPage,Math.max(0,Math.ceil(rows.length/12)-1)),view=rows.slice(page*12,page*12+12),share=state.patternMeasure==='share';
    const independent=s.sections.filter(p=>p.key!==s.source&&p.key!=='Hand1_late');
    const repeated=rows.filter(g=>independent.filter(p=>g.comparisons[p.key].classification==='inverted').length>=2).length;
    const repeatEligible=rows.filter(g=>independent.filter(p=>g.comparisons[p.key].eligible).length>=2).length;
    const crossing=rows.filter(g=>g.comparisons[state.patternTarget].crossMajority).length,cc=data.summary.byTarget[state.patternTarget].counts;
    const groupName=state.patternMode==='pairs'?'pairs':'pools';
    const inversion=rows.find(g=>g.comparisons[state.patternTarget].classification==='inverted');
    const bothRise=rows.filter(g=>{const a=g.bySection[s.source],b=g.bySection[state.patternTarget];return g.comparisons[state.patternTarget].crossMajority&&b.kRate>a.kRate&&b.tRate>a.tRate;});
    // Every family scale uses all five saved cohorts, so changing the target does not rescale it.
    const familyMax=g=>Math.max(1,...s.sections.flatMap(p=>[g.bySection[p.key].kRate,g.bySection[p.key].tRate]));
    const globalCeiling=S.layout({kRate:Math.max(1,...data.allGroups.map(familyMax)),tRate:0},{kRate:0,tRate:0}).ceiling;
    const chosen=rows.find(g=>g.id===state.patternExpanded);
    return `<section class="ef-story"><p class="ef-purpose">These charts test the proposed K/T frequency exchange. Compare each family’s early Herbal A ${share?'proportions':'frequencies'} with the same later section.</p>
      <div class="ef-controls"><label for="ef-target">Compare early A with<select id="ef-target" data-pattern-control="patternTarget">${s.sections.filter(p=>p.key!==s.source).map(p=>opt(p.key,names[p.key],state.patternTarget)).join('')}</select></label><label for="ef-mode">Word groups<select id="ef-mode" data-pattern-control="patternMode">${opt('pools','Complete rule pools',state.patternMode)}${opt('pairs','Exact K/T pairs',state.patternMode)}</select></label><div class="ev-seg" aria-label="Chart measure">${[['rate','Frequencies'],['share','Shares']].map(([v,l])=>`<button data-pattern-measure="${v}" aria-pressed="${v==='share'?share:!share}">${l}</button>`).join('')}</div><details class="ef-options" data-pattern-disclosure="options"><summary>Display options</summary><label for="ef-min">Minimum observations in each compared section<select id="ef-min" data-pattern-control="patternMin">${[1,5,10,20].map(x=>opt(x,x,state.patternMin)).join('')}</select></label><label><input type="checkbox" data-pattern-control="patternScale" ${state.patternScale==='global'?'checked':''}> Use the same frequency scale for every group</label><p>Each family’s frequency scale stays fixed when the comparison changes. The shared scale also stays fixed. Share charts always run from 0% to 100%.</p></details></div>
      <div class="ef-result"><p>${rows.length?`In ${names[state.patternTarget]}, the K and T lines cross in <strong>${crossing} of ${rows.length} ${groupName}</strong>. ${cc.inverted===1?`Only <strong>${label(s,inversion)}</strong> matches an approximately inverted early K/T ratio.`:`<strong>${cc.inverted}</strong> match an approximately inverted early K/T ratio.`}`:`No ${groupName} meet the observation minimum for ${names[state.patternTarget]}.`}</p>${rows.length?'<p>Crossing means K and T change order. Inversion also tests how closely their proportions reverse.</p>':''}</div>
      <div class="ef-chart-note"><span>${share?'Share of each group':'Occurrences per 10,000 section words'}</span><span class="ef-line-key"><i class="ef-key-k"></i>K <i class="ef-key-t"></i>T</span>${share?'<span>◇ Expected K after inversion</span>':''}<span>At least ${state.patternMin} observations in both sections${share?'':state.patternScale==='global'?' · one scale across families':' · scales differ between families'}</span></div>
      <div class="ef-family-grid">${view.map(g=>{const a=g.bySection[s.source],b=g.bySection[state.patternTarget];
        const ceiling=share?100:state.patternScale==='global'?globalCeiling:S.layout({kRate:familyMax(g),tRate:0},{kRate:0,tRate:0}).ceiling;
        const x=share?{kRate:a.share*100,tRate:(1-a.share)*100}:a,y=share?{kRate:b.share*100,tRate:(1-b.share)*100}:b;
        return `<article class="ef-family-card ${chosen?.id===g.id?'selected':''}"><h3><code>${label(s,g)}</code></h3><div class="ef-card-meta">${g.mode==='pairs'?'Spelling pair':'Pool '+esc(g.id)} · ${g.words.length} spellings</div>${S.svg(x,y,{sourceLabel:'Early A',targetLabel:names[state.patternTarget],ceiling,valueSuffix:share?'%':'',unitLabel:share?'share of family':'per 10,000 words',...(share?{inversionReference:(1-a.share)*100}:{})})}<footer><span>${a.total} early observations · ${b.total} later</span><button class="wb-button" data-pattern-expand="${esc(g.id)}" aria-expanded="${chosen?.id===g.id}">${chosen?.id===g.id?'Close details':'Counts and ratios'}</button></footer></article>${chosen?.id===g.id?counts(s,g,state):''}`;
      }).join('')||'<p>No groups meet this observation minimum.</p>'}</div>
      ${rows.length>12?`<div class="ep-pages"><button class="wb-button" data-pattern-page="${page-1}" ${page===0?'disabled':''}>Previous groups</button><span>${page*12+1}–${Math.min(rows.length,page*12+12)} of ${rows.length}</span><button class="wb-button" data-pattern-page="${page+1}" ${(page+1)*12>=rows.length?'disabled':''}>Next groups</button></div>`:''}
      ${rows.length?`<section class="ef-conclusion"><h3>Interpret the ratios</h3><p>${bothRise.length?`Both K and T frequencies rise in ${bothRise.length} of the ${crossing} crossing ${groupName}. Their proportions change even though T becomes more frequent in absolute terms. `:''}The ratio test compares the later K share with the early T share. Counts and ratios shows both the inverted and unchanged predictions beside the observation.</p><p>Optional t → k accounting measures added frequency coverage under the existing rules. It does not establish a reciprocal inversion.</p></section>`:''}
      <details class="ef-method" data-pattern-disclosure="method"><summary>Method and full results</summary><h4>Selection</h4><p>Every qualifying group appears, in alphabetical order. Selection uses combined K+T counts in early A and ${names[state.patternTarget]}, never the direction of change. ${rows.length} of ${data.allGroups.length} groups qualify. Even ten observations can produce unstable proportions.</p><h4>Grouping</h4><p>Complete rule pools retain overlapping donors such as ol, chy and edy. Membership follows the saved union of candidate transformations, including alternatives outside the current default menu. Exact pairs hold every character except k/t fixed and may split those donors. Neither grouping establishes shared meaning. Counts and ratios exposes all sections, every spelling and the inversion calculation.</p><h4>Populations</h4><p>Early and late Herbal A use the existing study cohorts. Pharma is the pharmaceutical section. Herbal B includes herbal material only. f76r belongs to Bio. These comparisons do not establish writing chronology. Rates divide by all section words. The inventory keeps q distinct and excludes P/F and atomic bench gallows.</p><p>Late A + Pharma is a pooled comparison, not another independent section. It is available in the comparison selector and every detail table.</p><h4>Ratio results</h4><p>The inversion test requires the later K share to be within ten percentage points of the inverted early share and ten points closer to it than to the unchanged share. This descriptive tolerance is not a statistical confidence test.</p><div class="ef-class-table"><table class="ev-table"><thead><tr><th>Outcome in ${names[state.patternTarget]}</th><th>Groups</th></tr></thead><tbody>${Object.entries(cc).map(([k,v])=>`<tr><th>${classes[k]}</th><td>${v}</td></tr>`).join('')}</tbody></table></div><p>${repeatEligible?`Repeated inversion occurs in ${repeated} of ${repeatEligible} groups with adequate observations in two independent later sections.`:'No groups qualify to test repeated inversion.'}</p><p>The earlier ratio study used narrower pools and merged some q variants. It found one repeated inversion pool. These charts recount the broader exact-q inventory used by this app. Optional allocation gains are not counts of inverted families.</p><button class="wb-button" data-pattern-export>Export all selected observations</button></details>
      <details class="ef-terms" data-pattern-disclosure="terms"><summary>Transcription terms</summary><p>K and T are transcription labels for two gallows glyphs. Herbal A and Herbal B combine illustration groups with Currier language classification. Pool names abbreviate members connected by candidate rules. They do not include every word with that prefix. Ellipses indicate multiple endings. Exact K/T pairs hold every character except k or t fixed. Counts and ratios lists the exact members.</p></details>
    </section>`;
  }
  function bind(host,s,state,onChange,inspect){
    host.querySelectorAll('[data-pattern-control]').forEach(el=>el.onchange=()=>{const key=el.dataset.patternControl;state[key]=key==='patternScale'?(el.checked?'global':'family'):key==='patternMin'?Number(el.value):el.value;state.patternPage=0;state.patternExpanded='';onChange();});
    host.querySelectorAll('[data-pattern-measure]').forEach(el=>el.onclick=()=>{state.patternMeasure=el.dataset.patternMeasure;onChange();});
    host.querySelectorAll('[data-pattern-expand]').forEach(el=>el.onclick=()=>{state.patternExpanded=state.patternExpanded===el.dataset.patternExpand?'':el.dataset.patternExpand;onChange();});
    host.querySelectorAll('[data-pattern-inspect]').forEach(el=>el.onclick=()=>inspect(el.dataset.patternInspect));
    host.querySelectorAll('[data-pattern-page]').forEach(el=>el.onclick=()=>{state.patternPage=Number(el.dataset.patternPage);state.patternExpanded='';onChange();});
    host.querySelector('[data-pattern-export]').onclick=()=>{const d=C.build(s,{mode:state.patternMode,minimum:state.patternMin,target:state.patternTarget});const url=URL.createObjectURL(new Blob([JSON.stringify({schema:1,sections:s.sections,options:d.options,summary:d.summary,groups:d.groups},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='echo-kt-family-observations.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  }
  root.EchoEvidencePatterns={html,bind,label,details:counts};
})(window);
